name: Android CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decrypt Google Services config file
      run: openssl aes-256-cbc -md sha256 -d -in mobile/google-services.aes -out mobile/google-services.json -k ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}

    - name: Build with Gradle
      run: ./gradlew build

    - name: Display dependency updates
      run: ./gradlew dependencyUpdates
